# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "9fc04877f410372261430933b0b502ce"
name = "love-and-money"
application_url = "https://macromedia-featuring-terrorists-vp.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "codem-teststore.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_customers,write_products"

[auth]
redirect_urls = [
  "https://macromedia-featuring-terrorists-vp.trycloudflare.com/auth/callback",
  "https://macromedia-featuring-terrorists-vp.trycloudflare.com/auth/shopify/callback",
  "https://macromedia-featuring-terrorists-vp.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[app_proxy]
url = "https://macromedia-featuring-terrorists-vp.trycloudflare.com"
subpath = "loveandmoney"
prefix = "apps"

[pos]
embedded = false
